### ISSUE TITLE
Plugin not work on Redmine 4.1.2 stable

### ISSUE THREAD

**Issue by keineahnung2345** [xelkano/redmine_xapian#110]
When I tried to search, it show "Internal server error" and following is the log:
```
Started GET "/search?utf8=%E2%9C%93&scope=&q=%E6%AD%90%E7%BE%8E" for 192.168.1.34 at 2021-04-16 17:14:40 +0800
Processing by SearchController#index as HTML
  Parameters: {"utf8"=>"✓", "scope"=>"", "q"=>"歐美"}
  Current user: admin (id=1)
[full-text-search][search] {"search_id":"1618564480.228078","q":"歐美","scope":"","all_words":"1","titles_only":"0","attachments":"1","open_issues":"0","offset":0,"limit":10,"order_target":"score","order_type":"desc","options":"0","issues":"1","news":"1","documents":"1","changesets":"1","wiki_pages":"1","messages":"1","projects":"1","changes":"1","tags":[],"user_id":1,"project_id":null,"n_hits":0,"total_n_hits":0,"elapsed_time":0.000125885009765625,"timestamp":"2021-04-16T09:14:40Z"}
  Rendering plugins/redmine_xapian/app/views/search/index.html.erb within layouts/base
  Rendered plugins/redmine_xapian/app/views/search/index.html.erb within layouts/base (3.7ms)
Completed 500 Internal Server Error in 43ms (ActiveRecord: 27.1ms)

ActionView::Template::Error (undefined method `each' for nil:NilClass):
    41: <fieldset class="box">
    42: <legend><%= toggle_checkboxes_link('p#search-types input') %></legend>
    43: <p id="search-types">
    44:   <% @object_types.each do |t| %>
    45:     <label>
    46:       <%= check_box_tag t, 1, @scope.include?(t) %>
    47:       <%# Plugin change do %>

plugins/redmine_xapian/app/views/search/index.html.erb:44:in `block in _plugins_redmine_xapian_app_views_search_index_html_erb__3119897427522166876_70166354237640'
plugins/redmine_xapian/app/views/search/index.html.erb:26:in `_plugins_redmine_xapian_app_views_search_index_html_erb__3119897427522166876_70166354237640'
lib/redmine/sudo_mode.rb:65:in `sudo_mode'
```
Following is my environment:
```
Environment:
  Redmine version                4.1.2.stable
  Ruby version                   2.6.6-p146 (2020-03-31) [x86_64-linux]
  Rails version                  5.2.4.5
  Environment                    production
  Database adapter               PostgreSQL
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
```

**Comment by picman** [comment]
It seems that the variable `@object_types` is nil. That's very unusual. In the controller I see:
```ruby
@object_types = Redmine::Search.available_search_types.dup
```
so I'd say that `@object_types` cannot be nil. It doesn't seem to be related to Redmine 4.1.2. Something else must have gone wrong. Is it a fresh installation or have you upgraded from v4.1.1? Redmine and plugins migrated without any errors?

**Comment by keineahnung2345** [comment]
Thanks for your reply. It's a fresh installation for Redmine, and I've got some errors during migration. I will look into this problem later.

**Comment by keineahnung2345** [comment]
I later found that it was because I have another plugin "full_text_search" installed, after I uninstall that plugin, redmine_xapian starts to work as expected.
